# .swiftlint.yml - Базовая конфигурация для современного Swift-проекта

### 1. Исключения (Excluded) ###
# Первым делом исключаем папки, которые не нужно проверять.
# Это ускоряет работу SwiftLint и предотвращает ложные срабатывания.
excluded:
#  - Pods # Зависимости CocoaPods
#  - Carthage # Зависимости Carthage
#  - DerivedData # Сгенерированные Xcode файлы
#  - .build # Папка сборки Swift Package Manager
#  - fastlane # Скрипты автоматизации
#  - vendor # Сторонние библиотеки (если есть)

### 2. Включаемые правила (Opt-in Rules) ###
# Эти полезные правила не входят в стандартный набор, но их стоит включить.
opt_in_rules:
  - empty_count # Рекомендует использовать `.isEmpty` вместо `.count == 0`
  - empty_string # Рекомендует использовать `isEmpty` вместо сравнения с ""
  - closure_end_indentation # Консистентный отступ для замыканий
  - first_where # Предлагает использовать `.first(where:)` вместо `.filter { ... }.first`
  - sorted_imports # Автоматически сортирует импорты
  - number_separator # Рекомендует разделители разрядов в больших числах (1_000_000)
  - yoda_condition # Запрещает условия в стиле "Йоды" (`if 42 == value` -> `if value == 42`)

  - discouraged_object_literal
  - unused_closure_parameter
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - redundant_type_annotation
  - redundant_string_enum_value
  - force_unwrapping

  # === НОВЫЕ ДОБАВЛЕНИЯ ===
  # Критически важные правила безопасности
  - implicitly_unwrapped_optional # Запрещает опасные Type! (кроме @IBOutlet)
  - unowned_variable_capture      # Предупреждает о потенциальных циклах в замыканиях
  - fatal_error_message           # Требует сообщение для fatalError()
  - legacy_cggeometry_functions   # Заставляет использовать CGRect(x:) вместо CGRectMake()
  - legacy_nsgeometry_functions   # Аналогично для NSRect
  - unused_optional_binding       # Ловит неиспользуемые if let

  # Правила для чистоты асинхронного/современного кода
#  - closure_body_length           # Контролирует размер замыканий
  - unavailable_function          # Предупреждает о вызове @available функций
  - strict_fileprivate            # Запрещает fileprivate в расширениях (encourages private)
  - operator_usage_whitespace     # Следит за пробелами вокруг операторов
  - multiline_arguments           # Единообразие для многострочных аргументов
  - toggle_bool                   # Рекомендует `bool.toggle()` вместо `bool = !bool`

### 3. Правила, которые можно сразу отключить (Disabled Rules) ###
# Эти правила часто вызывают споры или не подходят для всех проектов.
# Можно начать с их отключения.
disabled_rules:
  - identifier_name # Слишком строгое правило для имен переменных/констант. Часто конфликтует с внешними API (JSON, UIKit).
  - function_parameter_count # Ограничивает кол-во параметров. Может мешать в некоторых архитектурных подходах.
  - todo # Предупреждает о TODO-комментариях. Лучше следить за ними самому, чем получать предупреждения в билде.
  - comment_spacing

### 4. Настройка строгости ключевых правил ###
# Устанавливаем пороги для "warning" (желтое предупреждение) и "error" (красная ошибка, ломающая билд).
line_length:
  warning: 120 # Предупреждение после 160 символов
  error: 160   # Ошибка после 200 символов
  ignores_comments: true # Игнорировать комментарии
  ignores_urls: true     # Игнорировать длинные URL в строке

function_body_length:
  warning: 50  # Функция на 50 строк - предупреждение
  error: 100   # Функция на 100 строк - ошибка

type_body_length:
  warning: 300  # Предупреждение для типа (класс/структура) на 300 строк
  error: 500    # Ошибка для типа на 500 строк

file_length:
  warning: 500  # Функция на 50 строк - предупреждение
  error: 800    # Функция на 100 строк - ошибка

cyclomatic_complexity:
  warning: 12   # Цикломатическая сложность > 12 - предупреждение
  error: 20     # Цикломатическая сложность > 20 - ошибка





trailing_comma:
  severity: error
  mandatory_comma: true

vertical_whitespace:
  max_empty_lines: 2

force_unwrapping:
  severity: warning # Сначала пусть будет предупреждением

force_try:
  severity: warning

force_cast:
  severity: warning

implicitly_unwrapped_optional:
  severity: warning # Сначала предупреждение, потом можно перевести в error

unowned_variable_capture:
  severity: warning

# Настройка для контроля замыканий
#closure_body_length:
#  warning: 30
#  error: 50

# Правила для аккуратных многострочных выражений
multiline_arguments:
  first_argument_location: next_line # или 'same_line'
  only_enforce_after_first_closure_on_first_line: true

large_tuple:
    warning: 3
    error: 5


### 5. Формат отчета и общие настройки ###
reporter: "xcode" # Формат вывода, который Xcode понимает как кликабельные предупреждения
analyzer_rules: # Включаем правила анализатора (более глубокий статический анализ)
  - explicit_self
