# .swiftlint.yml - Базовая конфигурация для современного Swift-проекта

### 1. Исключения (Excluded) ###
# Первым делом исключаем папки, которые не нужно проверять.
# Это ускоряет работу SwiftLint и предотвращает ложные срабатывания.
excluded:
  - Pods # Зависимости CocoaPods
  - Carthage # Зависимости Carthage
  - DerivedData # Сгенерированные Xcode файлы
  - .build # Папка сборки Swift Package Manager
  - fastlane # Скрипты автоматизации
  - vendor # Сторонние библиотеки (если есть)

### 2. Включаемые правила (Opt-in Rules) ###
# Эти полезные правила не входят в стандартный набор, но их стоит включить.
opt_in_rules:
  - empty_count # Рекомендует использовать `.isEmpty` вместо `.count == 0`
  - empty_string # Рекомендует использовать `isEmpty` вместо сравнения с ""
  - closure_end_indentation # Консистентный отступ для замыканий
  - first_where # Предлагает использовать `.first(where:)` вместо `.filter { ... }.first`
#  - sorted_imports  Автоматически сортирует импорты
  - number_separator # Рекомендует разделители разрядов в больших числах (1_000_000)
  - yoda_condition # Запрещает условия в стиле "Йоды" (`if 42 == value` -> `if value == 42`)

### 3. Правила, которые можно сразу отключить (Disabled Rules) ###
# Эти правила часто вызывают споры или не подходят для всех проектов.
# Можно начать с их отключения.
disabled_rules:
  - identifier_name # Слишком строгое правило для имен переменных/констант. Часто конфликтует с внешними API (JSON, UIKit).
  - function_parameter_count # Ограничивает кол-во параметров. Может мешать в некоторых архитектурных подходах.
  - todo # Предупреждает о TODO-комментариях. Лучше следить за ними самому, чем получать предупреждения в билде.
  - comment_spacing

### 4. Настройка строгости ключевых правил ###
# Устанавливаем пороги для "warning" (желтое предупреждение) и "error" (красная ошибка, ломающая билд).
line_length:
  warning: 120 # Предупреждение после 160 символов
  error: 160   # Ошибка после 200 символов
  ignores_comments: true # Игнорировать комментарии
  ignores_urls: true     # Игнорировать длинные URL в строке

function_body_length:
  warning: 50  # Функция на 50 строк - предупреждение
  error: 100   # Функция на 100 строк - ошибка

type_body_length:
  warning: 300  # Предупреждение для типа (класс/структура) на 300 строк
  error: 500    # Ошибка для типа на 500 строк

file_length:
  warning: 500  # Функция на 50 строк - предупреждение
  error: 800    # Функция на 100 строк - ошибка

cyclomatic_complexity:
  warning: 12   # Цикломатическая сложность > 12 - предупреждение
  error: 20     # Цикломатическая сложность > 20 - ошибка





trailing_comma:
  severity: error
  mandatory_comma: true

vertical_whitespace:
  max_empty_lines: 2



### 5. Формат отчета и общие настройки ###
reporter: "xcode" # Формат вывода, который Xcode понимает как кликабельные предупреждения
analyzer_rules: # Включаем правила анализатора (более глубокий статический анализ)
  - explicit_self
